# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubBrowser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubBrowser
	pod 'Kingfisher', '~> 6.0'
  pod 'NVActivityIndicatorView'
  pod 'Down'
  pod 'RealmSwift'
  pod 'Moya', '~> 14.0'
  pod "PromiseKit", "~> 6.8"
end
